version: 1
handlers:
  stream_handler:
    class: logging.StreamHandler
    level: NOTSET
    formatter: stream_formatter
    stream: ext://sys.stdout

formatters:
  stream_formatter:
    format: '%(asctime)s [%(levelname)s] %(filename)s %(funcName)s(): %(message)s'
    datefmt: ''
  default_formatter:
    format: '{"asctime": "%(asctime)s", "level": "%(levelname)s", "func": "%(funcName)s", "message": "%(message)s"}'
    datefmt: ''

loggers:
  root:
    level: NOTSET
    handlers: []
  app:
    level: INFO
    handlers:
      - stream_handler
    propagate: true